// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://axeiowwlofkmouwnrrid.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF4ZWlvd3dsb2ZrbW91d25ycmlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMjMzMjEsImV4cCI6MjA2NTU5OTMyMX0.RnptgE7d57PvD0I-od61yHRlnA3_h_ijn-W2h2AUIh4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);